/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.feesmanagementsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class SignUpPage extends javax.swing.JFrame {

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
    }
    
    int id=0;
    int getId()
    {
        ResultSet rs=null;
          try
        {
         Class.forName("com.mysql.cj.jdbc.Driver");
         String url="jdbc:mysql://localhost:3306/fmsdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL [root on Default schema]";
         Connection con =DriverManager.getConnection(url, "root", "root");
         String sql="select max(id) from signup";
         Statement st= con.createStatement();
         rs=st.executeQuery(sql);
         while(rs.next())
         {
             id++;
            // id=getInt(1);
         }
        }catch(Exception e)
        {
           e.printStackTrace();
        }
        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcnumber = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        txtlname = new javax.swing.JTextField();
        txtcpfield = new javax.swing.JPasswordField();
        txtuname = new javax.swing.JTextField();
        txtpfield = new javax.swing.JPasswordField();
        txtdob = new com.toedter.calendar.JDateChooser();
        btnlogin = new javax.swing.JButton();
        btnsignup = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        lblcpassworderror = new javax.swing.JLabel();
        lblcnumbererror = new javax.swing.JLabel();
        lblpassworderror1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Contact Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("First Name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Confirm Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("D.O.B.");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        txtcnumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtcnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcnumberActionPerformed(evt);
            }
        });
        txtcnumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcnumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcnumberKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcnumberKeyTyped(evt);
            }
        });
        getContentPane().add(txtcnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 220, -1));

        txtfname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 220, -1));

        txtlname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 220, -1));

        txtcpfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtcpfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 220, 30));

        txtuname.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 220, -1));

        txtpfield.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpfieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpfieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpfieldKeyTyped(evt);
            }
        });
        getContentPane().add(txtpfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 220, 30));
        getContentPane().add(txtdob, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 220, 30));

        btnlogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnlogin.setText("Login");
        getContentPane().add(btnlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 120, 40));

        btnsignup.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnsignup.setText("Sign Up");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 120, 40));

        btnclear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        getContentPane().add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 120, 40));

        lblcpassworderror.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblcpassworderror.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblcpassworderror, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 270, 20));

        lblcnumbererror.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblcnumbererror.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblcnumbererror, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 270, 20));

        lblpassworderror1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblpassworderror1.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblpassworderror1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 270, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        validation();
        if(validation()){
            insertData();
        }else{
            JOptionPane.showMessageDialog(this, "Validation Issue.");
        }
    }//GEN-LAST:event_btnsignupActionPerformed

    private void txtpfieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyPressed
        passwordCheck();
    }//GEN-LAST:event_txtpfieldKeyPressed

    private void txtpfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyReleased
        passwordCheck();
    }//GEN-LAST:event_txtpfieldKeyReleased

    private void txtpfieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpfieldKeyTyped
        passwordCheck();
    }//GEN-LAST:event_txtpfieldKeyTyped

    private void txtcnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcnumberActionPerformed

    private void txtcnumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnumberKeyPressed
       contactNumCheck();
    }//GEN-LAST:event_txtcnumberKeyPressed

    private void txtcnumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnumberKeyReleased
      contactNumCheck();
    }//GEN-LAST:event_txtcnumberKeyReleased

    private void txtcnumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcnumberKeyTyped
        contactNumCheck();
    }//GEN-LAST:event_txtcnumberKeyTyped
    
    String fname, lname, uname, password, cpassword,mnumber;
    Date dob;
    
    void insertData()
    {
        SimpleDateFormat s1=new SimpleDateFormat("yyyy-MM-dd");
        String dob1=s1.format(dob);
        try
        {
         Class.forName("com.mysql.cj.jdbc.Driver");
         String url="jdbc:mysql://localhost:3306/fmsdatabase?zeroDateTimeBehavior=CONVERT_TO_NULL [root on Default schema]";
         Connection con =DriverManager.getConnection(url, "root", "root");
         String sql="insert into signup value(?,?,?,?,?,?,?)";
         PreparedStatement st=con.prepareStatement(sql);
         st.setInt(1, getId());
         st.setString(2, fname);
         st.setString(3, lname);
         st.setString(4, uname);
         st.setString(5, password);
         st.setString(6, dob1);
         st.setString(7, mnumber);
         int i=st.executeUpdate();
         if(i>0){
             JOptionPane.showMessageDialog(this, "Record Inserted Succesfully");
         }else{
             JOptionPane.showMessageDialog(this, "Record Not Inserted Succesfully");
         }
         
         
         
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    
    
    boolean validation(){
        fname = txtfname.getText();
        lname = txtlname.getText();
        uname = txtuname.getText();
        password = txtpfield.getText();
        cpassword = txtcpfield.getText();
        dob = txtdob.getDate();
        mnumber = txtcnumber.getText();
        
        if(fname.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter First Name.........");
            return false;
        }
        if(lname.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Last Name.........");
             return false;
        }
        if(uname.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter User Name........." );
             return false;
        }
        if(password.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Password........." );
             return false;
        } 
        if(cpassword.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Confirm Password........." );
             return false;
        }
         if(dob.equals(null)){
            JOptionPane.showMessageDialog(this, "Please Enter Date Of Birth........." );
             return false;
        }
         if(mnumber.equals("")){
            JOptionPane.showMessageDialog(this, "Please Enter Contact Number........." );
             return false;
        }
         return true;       
    }
    
    void passwordCheck()
    {
        password = txtpfield.getText();
        if(password.length()>8){
            lblcnumbererror.setText("");
        }else{
            lblcnumbererror.setText("Enter 8 Digit Password.");
        }
        
    }
    
    void contactNumCheck(){
        mnumber = txtcnumber.getText();
        if(mnumber.length()==10){
            lblcnumbererror.setText("");
        }else{
            lblcnumbererror.setText("Enter 10 Digit Contact Number");
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUpPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnlogin;
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblcnumbererror;
    private javax.swing.JLabel lblcpassworderror;
    private javax.swing.JLabel lblpassworderror1;
    private javax.swing.JTextField txtcnumber;
    private javax.swing.JPasswordField txtcpfield;
    private com.toedter.calendar.JDateChooser txtdob;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JPasswordField txtpfield;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
